name: Tests

on:
  [push, pull_request]
jobs:
  gradleTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: "Setup Java"
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: "Gradle test"
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: test
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
